# Generated by Django 5.1.2 on 2024-10-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_code_image',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
