# Generated by Django 5.1.2 on 2024-10-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_qr_code_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qr_code_image',
        ),
    ]
